#[theme]
#primaryColor = "#008080"
#backgroundColor = "#19859A"
#secondaryBackgroundColor = "#E2A6A6"
#textColor = "#010002"
#font = "sans serif"

[theme]
primaryColor = "#3EE1D0"
backgroundColor = "#0F1417"
secondaryBackgroundColor = "#1B2429"
textColor = "#D0D6D8"
font = "sans serif"



