#[theme]
#primaryColor = "#008080"
#backgroundColor = "#19859A"
#secondaryBackgroundColor = "#E2A6A6"
#textColor = "#010002"
#font = "sans serif"

[theme]
primaryColor = "#6A5ACD"       # soft indigo
backgroundColor = "#FAF9F7"    # warm off-white
secondaryBackgroundColor = "#EFE7DD"
textColor = "#1C1C1C"
font = "sans serif"


