#[theme]
#primaryColor = "#008080"
#backgroundColor = "#19859A"
#secondaryBackgroundColor = "#E2A6A6"
#textColor = "#010002"
#font = "sans serif"

[theme]
primaryColor = "#008080"
backgroundColor = "#F2F8F9"
secondaryBackgroundColor = "#D9EFF0"
textColor = "#042D2D"
font = "sans serif"

